mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bookbook.dto

debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.com.bookbook: debug
    org.springframework.web.servlet: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookbook
    username: wisdom
    password: asdfasdf33
